# .github/workflows/ci.yml
# Simple CI workflow to get started quickly
name: Simple CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Downloads Unity automatically

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Build and test
        run: |
          mkdir build && cd build
          cmake ..
          make
          ./test_runner

      - name: Show test results
        if: always()  # Run even if tests fail
        run: |
          echo "✅ CI/CD is working!"
          echo "🧪 Unity tests completed"